### ISSUE TITLE
Decide when to get file sizes and allocate buffers

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/light-speed-io#22]
Should the optimization step should be responsible for allocating the memory buffers?

Although we'll first need to `stat` files where we don't yet know the size of the buffers.

 But! Should we only allocate memory buffers when we're actually ready to read? Say we want to read 1,000,000 chunks. Using io_uring, we won't actually submit all 1,000,000 read requests at once: instead we'll keep the submission ring topped up with, say, 64 tasks. If the user wants all 1,000,000 chunks returned then we have no option but to allocate (and keep) all 1,000,000 chunks. But if, instead, the user wants each chunk to be processed and then moved into a common final array, then we only have to keep 64 buffers around at any given time.

~~Also: if we open files to get their sizes, then should we keep them open for reading? What about if LSIO is asked to load 1 million files for which we don't know their sizes?~~ UPDATE: `statx` takes a _pathname_, so we don't need to `open` a file before calling `statx`. (See [statx io_uring docs](https://docs.rs/io-uring/latest/io_uring/opcode/struct.Statx.html). and [statx Linux docs](https://man7.org/linux/man-pages/man2/statx.2.html))

xref: #21

## TODO

- [ ] Make decision
- [ ] Update design doc

**Comment by JackKelly** [comment]
Maybe the solution is to have _two separate_ API methods: something like:

* `read`:  LSIO creates buffers. But cannot re-use buffers.
* `read_into`: User supplies buffer. LSIO cannot re-use buffers.
* `read_and_process`: LSIO creates buffers _and_ can re-use buffers.
* `write`
* `process_and_write`

TODO:
- [ ] Rename `IO_Operations_For_File` back to `FileChunks`, and remove the `io_type` field. And maybe copy the HTTP GET ranges names and symantics?
- [ ] Need a way to express that the user must supply buffers for `write`. Maybe have separate `WriteChunks` and `ReadChunks` (which can have `buffers=Auto`)? Or maybe have separate `ReadInto` (which accepts a user-defined buffer) and `Read` (which automatically defines a buffer).
- [ ] Have separate methods for read and write (instead of using `io_type` to set if it's read or write).
- [ ] Add the four new methods into the design?

**Comment by JackKelly** [comment]
Some outstanding questions and thoughts:

1. How to handle this use-case: Load compressed Zarrs, and decompress directly into a user-specified buffer (e.g. directly into a part of the numpy array). Some options:
  - Include a new method like `read_and_transform(chunks: FileChunksWithBuffers, transform) -> Vec<Result<_>>`.
  - Or, change `read_and_map` to return a `Vec<Result<Option<[u8]>>>`. If `map` returns nothing then return `None`.
2. For methods which _only_ return an error (like methods which return `Vec<Result<_>>`) it might be useful to have a binary flag to say "at least one error has occurred". We don't want to have to loop through a million `Result`s only to find that no errors have occurred!
3. How to allow the user to see the correspondence between each file chunk, and each returned `Result`? Some options:
  - Always sort the `Vec<Result>` to be in the same order as the chunks submitted by the user. That feels sub-optimal because we'll either need to sort the results at the end, or we'll need to put the results into a pre-allocated vector, perhaps using a different thread.
  - Define a new struct. Something like `IOResult`. Then return a `Vec<IOResult>`. The `IOResult` struct will have fields which describe the IO operation. And include a `Result<u8>` or a `Result<Option<u8>>`.
4. What about rechunking / moving data from, say, GRIB to Zarr?
  - Should we add a `read_then_write` method for copying data (unmodified). This can all be done by a single io_uring chain.
  - Should we add a `read_map_write` method for when we need to do some processing (and so io_uring can't do the whole processing chain in one go).
5. Should we add a `read_and_map_in_order` method which reads in arbitrary order, but then calls the `map` function _in order_ (for Vincent's use-case of processing data in a streaming fashion)? Maybe don't worry about this for now?
6. Does the fact that we have all these methods suggest that I've got the "division of responsibilities" wrong? Should we re-consider just returning an iterator of `u8`s?
