### ISSUE TITLE
Update "Optimising the IO plan" section in `design.md`, according to the new API

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/light-speed-io#23]
Update "Optimising the IO plan" section in `design.md`, according to the new API discussed in issue #22.

## TODO

- [x] Delete the two type aliases `FileByteRanges` and `FileByteRangesWithBuffers`.
- [x] Define `struct ByteRanges(Vec<ByteRange>)` and `struct ByteRangesWithBuffers(Vec<ByteRangeWithBuffers>)`.
- [x] Define a `trait ByteRangeOptimiser` with methods like `merge_byte_ranges` and `split_large_byte_ranges` (with no default implementations).
- [x] Define custom implementations of `ByteRangeOptimiser` for `ByteRanges` and `ByteRangesWithBuffers`.
- [x] `Reader` methods would take a `HashMap<PathBuf, Vec<OptimisedByteRange>>` or `HashMap<PathBuf, Vec<OptimisedByteRangeWithBuffers>>`.
- [x] Users need to call a `ByteRangeOptimiser` method on the `ByteRanges` or `ByteRangesWithBuffers` before passing to the `Reader` methods. (This makes it easy for users to customise, including using different thresholds). If the user wants no optimisation, then implement `OptimisedByteRanges from ByteRanges` and `OptimisedByteRangesWithBuffers from ByteRangesWithBuffers`.
- [x] Fix problem with design: `ByteRanges.merge()` returns an `OptimisedByRange`; whilst `ByteRangesWithBuffers.merge()` returns an `OptimisedByteRangesWithBuffers`. But the declaration of `merge()` in the `ByteRangeOptimiser` trait can only return a single type! SOLUTION: Use an associated type!
