### ISSUE TITLE
Replace `OperationFuture` with `tokio::sync::oneshot`?

### ISSUE THREAD

**Issue by JackKelly** [JackKelly/light-speed-io#43]
Perhaps, instead of implementing our own custom `Future` (`OperationFuture`), it might be easier (and more efficient?) to use [`tokio::sync::oneshot`](https://docs.rs/tokio/1.36.0/tokio/sync/oneshot/index.html), as per [Alice Ryhl's blog post recommendation for using `tokio` with `rayon`](https://ryhl.io/blog/async-what-is-blocking/#the-rayon-crate)?

Specifically, maybe the `struct Operation` would include a field `send_output_to: Option<oneshot::Sender>`.

`ObjectStoreAdapter::get` would look something like this:

```rust
use tokio::sync::oneshot;
let (tx, rx) = oneshot::channel();
let operation = Operation::Get {
    location: location.clone(),
    buffer: None,
    send_output_to: Some(tx),
};
self.worker_thread.send(operation);
rx.await.expect("Panic in worker thread")
```

## Pros of using `oneshot` instead of `OperationFuture`:
- Simplifies LSIO. I think we can entirely remove `operation_future.rs` (71 LoC). And remove `OperationWithCallback` (about 30 LoC).
- Makes it easier to send a `Result` from `io_uring_local.rs` back to the user (#45).
- Might be faster?
    - We no longer need to `Box` every `callback`. Hence we we can avoid one heap allocation per operation.
    - We no longer need a `Mutex`.

## Cons of using `oneshot` instead of `OperationFuture`:
- Makes `tokio` a hard requirement

## TODO
- [x] Benchmark the existing code (using `OperationFuture`)
- [ ] Implement `oneshot` approach
- [ ] Benchmark `oneshot` approach
- ~~Try removing the `Box` in `OpTracker`, and see what the speed implications are, and how many page faults we get. (See #54)~~

**Comment by JackKelly** [comment]
Performance (on my Intel NUC) on `main`:

```
     Running benches/io_uring_local.rs (target/release/deps/io_uring_local-d557319dd99ba2ea)
Benchmarking load_1000_files/io_uring_local: Collecting 10 samples in estimated 5.6984 s (20 iterations
load_1000_files/io_uring_local
                        time:   [207.78 ms 210.58 ms 213.61 ms]
                        thrpt:  [1.1429 GiB/s 1.1594 GiB/s 1.1750 GiB/s]
                 change:
                        time:   [-58.118% -38.248% -6.8618%] (p = 0.07 > 0.05)
                        thrpt:  [+7.3674% +61.939% +138.76%]
                        No change in performance detected.
Benchmarking load_1000_files/local_file_system: Collecting 10 samples in estimated 9.1056 s (20 iterati
load_1000_files/local_file_system
                        time:   [397.58 ms 400.84 ms 403.92 ms]
                        thrpt:  [618.94 MiB/s 623.69 MiB/s 628.80 MiB/s]
                 change:
                        time:   [+1.1105% +2.0875% +3.1119%] (p = 0.00 < 0.05)
                        thrpt:  [-3.0180% -2.0449% -1.0983%]
                        Performance has regressed.

jack@jack-NUC:~/dev/rust/light-speed-io$ perf stat target/release/deps/io_uring_local-d557319dd99ba2ea 
io_uring_local --bench --profile-time 5
Benchmarking load_1000_files/io_uring_local: Complete (Analysis Disabled)


 Performance counter stats for 'target/release/deps/io_uring_local-d557319dd99ba2ea io_uring_local --bench --profile-time 5':

          5,987.58 msec task-clock                       #    1.239 CPUs utilized             
            44,483      context-switches                 #    7.429 K/sec                     
               705      cpu-migrations                   #  117.744 /sec                      
            68,401      page-faults                      #   11.424 K/sec                     
    20,497,858,273      cycles                           #    3.423 GHz                       
    29,238,104,335      instructions                     #    1.43  insn per cycle            
     6,359,888,104      branches                         #    1.062 G/sec                     
        15,793,219      branch-misses                    #    0.25% of all branches           

       4.832593203 seconds time elapsed

       0.155372000 seconds user
       5.858586000 seconds sys
```

**Comment by JackKelly** [comment]
Performance (on my Intel NUC) _after_ implementing `oneshot`: 

```
     Running benches/io_uring_local.rs (target/release/deps/io_uring_local-d557319dd99ba2ea)
Benchmarking load_1000_files/io_uring_local: Warming up for 2.0000 s
Warning: Unable to complete 10 samples in 5.0s. You may wish to increase target time to 8.6s.
Benchmarking load_1000_files/io_uring_local: Collecting 10 samples in estimated 8.5936 s (10 iterations
load_1000_files/io_uring_local
                        time:   [221.51 ms 230.14 ms 239.77 ms]
                        thrpt:  [1.0182 GiB/s 1.0608 GiB/s 1.1022 GiB/s]
                 change:
                        time:   [-21.848% -7.6751% +3.8043%] (p = 0.45 > 0.05)
                        thrpt:  [-3.6649% +8.3132% +27.956%]
                        No change in performance detected.

jack@jack-NUC:~/dev/rust/light-speed-io$ perf stat target/release/deps/io_uring_local-d557319dd99ba2ea io_uring_local --bench --profile-time 5
Benchmarking load_1000_files/io_uring_local: Complete (Analysis Disabled)


 Performance counter stats for 'target/release/deps/io_uring_local-d557319dd99ba2ea io_uring_local --bench --profile-time 5':

          6,205.63 msec task-clock                       #    1.235 CPUs utilized             
            45,178      context-switches                 #    7.280 K/sec                     
             1,102      cpu-migrations                   #  177.581 /sec                      
            50,208      page-faults                      #    8.091 K/sec                     
    20,896,514,171      cycles                           #    3.367 GHz                       
    30,142,505,520      instructions                     #    1.44  insn per cycle            
     6,631,236,034      branches                         #    1.069 G/sec                     
        15,694,413      branch-misses                    #    0.24% of all branches           

       5.026145053 seconds time elapsed

       0.147539000 seconds user
       6.087379000 seconds sys
```

**Comment by JackKelly** [comment]
OK, I can get the same bandwidth with `oneshot`, by running the benchmark immediately after creating the files with `fio`:

```
     Running benches/io_uring_local.rs (target/release/deps/io_uring_local-d557319dd99ba2ea)
Benchmarking load_1000_files/io_uring_local: Collecting 10 samples in estimated 5.0233 s (20 iterations
load_1000_files/io_uring_local
                        time:   [206.03 ms 208.93 ms 212.11 ms]
                        thrpt:  [1.1510 GiB/s 1.1685 GiB/s 1.1850 GiB/s]
                 change:
                        time:   [-75.334% -56.610% -7.0844%] (p = 0.13 > 0.05)
                        thrpt:  [+7.6245% +130.47% +305.42%]
                        No change in performance detected.
```
